// Generated by https://quicktype.io

// Folders
export interface FetchFoldersProps {
  id: number;
  attributes: FetchFoldersAttributes;
}

export interface FetchFoldersAttributes {
  name: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  userId: string;
  recordings: Recordings;
}

export interface Recordings {
  data: Datum[];
}

export interface Datum {
  id: number;
  attributes: DatumAttributes;
}

export interface DatumAttributes {
  title: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  userId: string;
}

// =====================

// Generated by https://quicktype.io

export interface RecordingsDataProps {
  id: number;
  attributes: RecordingsDataAttributes;
}

export interface RecordingsDataAttributes {
  title: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  userId: string;
  audio: Audio;
  tags: TagsProps;
  custom_folder: CustomFolder;
  notes: {
    data: CustomFolderData[];
  };
  duration: string;
}

export interface Audio {
  data: AudioData;
}

export interface AudioData {
  id: number;
  attributes: PurpleAttributes;
}

export interface PurpleAttributes {
  name: string;
  alternativeText: string;
  caption: string;
  width: null;
  height: null;
  formats: null;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl: null;
  provider: string;
  provider_metadata: null;
  createdAt: string;
  updatedAt: string;
}

export interface CustomFolder {
  data: CustomFolderData;
}

export interface CustomFolderData {
  id: number;
  attributes: FluffyAttributes;
}

export interface FluffyAttributes {
  name?: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  userId: string;
  content?: string;
}

export interface TagsProps {
  data: TagsDatum[];
}

export interface TagsDatum {
  id: number;
  attributes: DatumAttributes;
}

export interface DatumAttributes {
  title: string;
  description: null;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  userId: string;
}
